steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud projects add-iam-policy-binding $$PROJECT \
    --member=cb-dataflow-service-account@cb-dataflow-python.iam.gserviceaccount.com \
    --role=roles/iam.serviceAccountUser;
    gcloud functions deploy ${_FUNCTION_NAME} \
    --region=asia-northeast1 \
    --trigger-topic=pubsub-test-topic \
    --entry-point=cf_pubsub_trigger \
    --retry \
    --runtime=python37 \
    --service-account=cb-dataflow-service-account@cb-dataflow-python.iam.gserviceaccount.com
  env:
  - 'PROJECT=$PROJECT_ID'
substitutions:
  _FUNCTION_NAME: