steps:
- id: Install jq
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get upgrade
    curl -O http://ftp.au.debian.org/debian/pool/main/j/jq/jq_1.5+dfsg-2+b1_amd64.deb
    dpkg --install jq_1.5+dfsg-2+b1_amd64.deb
- id: Retrieve Service Account
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  volumes:
  - name: 'vol1'
    path: '/service_account_store'
  args:
  - '-c'
  - |
    gsutil cp gs://cb-dataflow-storage/cb-dataflow-python-23cc97500072.json /service_account_store/sa.json
- id: Deploy Cloud Function
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  volumes:
  - name: 'vol1'
    path: '/service_account_store'
  args:
  - '-c'
  - |
    cat /service_account_store/sa.json | jq '.client_email'
    gcloud functions deploy ${_FUNCTION_NAME} \
    --region=asia-northeast1 \
    --trigger-topic=pubsub-test-topic \
    --entry-point=cf_pubsub_trigger \
    --retry \
    --runtime=python37 \
    --set-env-vars SERVICE_ACCOUNT=`cat /service_account_store/sa.json`
  env:
  - 'PROJECT=$PROJECT_ID'
substitutions:
  _FUNCTION_NAME: