steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy ${_FUNCTION_NAME} \
    --region=asia-northeast1 \
    --trigger-topic=pubsub-test-topic \
    --entry-point=cf_pubsub_trigger \
    --retry \
    --runtime=python37 \
  env:
  - 'PROJECT=$PROJECT_ID'
substitutions:
  _FUNCTION_NAME: